version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - PORT=9000
      - MONGO_URI=mongodb://mongo:27017/expense-tracker
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: expense-tracker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
