FROM node:14-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

FROM node:14-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /app .
EXPOSE 9000

CMD ["npm", "start"]
