apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "9000"
  MONGO_URI: "mongodb://mongodb:27017/expense-tracker"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  JWT_SECRET: "c2VjcmV0LWtleS1mb3Itand0LXRva2Vu" # base64 encoded "secret-key-for-jwt-token"
